package data_structs

import (
	"text/template"
)

var HomePage = template.Must(template.ParseFiles("./static/index.html"))
var ErrorPage = template.Must(template.ParseFiles("./static/404Error.html"))
var DetailsPage = template.Must(template.ParseFiles("./static/details.html"))

type Artists struct {
	Artists []Artist
}

type Artist struct {
	Id           int      `json:"id"`
	Image        string   `json:"image"`
	Name         string   `json:"name"`
	Members      []string `json:"members"`
	CreationDate int      `json:"creationDate"`
	FirstAlbum   string   `json:"firstAlbum"`
	Locations    string   `json:"locations"`
	ConcertDates string   `json:"concertDates"`
	Relations    string   `json:"relations"`
}

type RelationsData struct {
	Index []Relations `json:"index"`
}

type LocationsData struct {
	Index []Locations `json:"index"`
}

type Locations struct {
	ID        int      `json:"id"`
	Locations []string `json:"locations"`
	Dates     string   `json:"dates"`
}

type DatesData struct {
	Index []Dates `json:"index"`
}

type Dates struct {
	ID    int      `json:"id"`
	Dates []string `json:"dates"`
}

type ArtistWithRelations struct {
	ID           int                    `json:"id"`
	Image        string                 `json:"image"`
	Name         string                 `json:"name"`
	Members      []string               `json:"members"`
	CreationDate int                    `json:"creationDate"`
	FirstAlbum   string                 `json:"firstAlbum"`
	Locations    string                 `json:"locations"`
	ConcertDates string                 `json:"concertDates"`
	Relations    Relations              `json:"relations"`
	Coordinates  map[string][][]float32 `json:"coordinates"`
}

type Relations struct {
	ID             int                 `json:"id"`
	DatesLocations map[string][]string `json:"datesLocations"`
}

type AutoGenerated struct {
	Results []struct {
		Geometry struct {
			Location struct {
				Lat float64 `json:"lat"`
				Lng float64 `json:"lng"`
			} `json:"location"`
		} `json:"geometry"`
	} `json:"results"`
	Status string `json:"status"`
}
